language: python

python:
  - 2.7

services:
  - docker

before_install:
- docker build -t mockssh .
- docker run -d -p 22:2201 --name mockssh mockssh
- docker ps -a
- docker inspect mockssh
- netstat -an | grep -w 2201

script:
  - cd alive
  - python createStatus.py --hostFile ../test/hosts2.json.test.orig --vendorFile ../test/vendorNodes.json.test --statusFile ../test/status.json.test
  - cp ../test/status.json.test ../test/status.json.test.orig
  - python test.py
