language: python

python:
  - 3.6

services:
  - docker

before_install:
#- docker build -t mockssh .
- ls -l

script:
  - docker build -t mockssh .
  - docker run -d -p 2222:2201 --name mockssh mockssh
  - docker ps -a
  - IP=$(docker inspect mockssh | grep IPAddress | tail -1 | awk '{print $2}' | tr -d '"' | tr -d ",")
  - echo IP address is $IP
  - netstat -an | grep 2201
  - netstat -an
  - ssh -p 2222 root@localhost
  

#   - cd alive
#   - python createStatus.py --hostFile ../test/hosts2.json.test.orig --vendorFile ../test/vendorNodes.json.test --statusFile ../test/status.json.test
#   - cp ../test/status.json.test ../test/status.json.test.orig
#   - python test.py
