version: 2
jobs:
  build:
        machine: true
        steps:
            - checkout
            - run:
                name: Install python
                command: |
                  sudo apt install -y python3 python
