version: 2
jobs:
  build:
        docker:
           - image: circleci/python:2.7

        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: build docker
                command: |
                   pwd
                   ls
                   docker build -t mockssh .

            - run:
                name: spin up docker
                command: |
                   docker run -d --name mockssh mockssh
                   pwd
                   ls

            - run:
                name: verify docker
                command: |
                   whoami
                   uname -a

                   docker ps -a
                   IP=$(docker inspect mockssh | grep -w IPAddress | awk '{print $2}' | tr -d '"' | tr -d ',' | tail -1)
                   echo $IP
                   echo $DOCKER_HOST
                   IP2=$(echo $DOCKER_HOST | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")
                   echo ping ip2
                   sudo ping c1 $IP2
                   sudo ip a
                   sudo ping -c1 $IP
                   sudo nc -z $IP 22
                   echo $?
                   #ssh testadmin@$IP
