version: 2
jobs:
  build:
    docker:
            - image: circleci/node:8.11

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: setup docker
          command: |
            docker pull owasp/zap2docker-stable
            docker run --name zap -u zap -p 8080:8080 -i owasp/zap2docker-stable zap.sh -daemon -host 0.0.0.0 -port 8080
          background: true

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

      - run:
          name: check docker
          command: docker ps -a
