version: 2
jobs:
  build:
        machine:
                image: ubuntu-1604:201903-01

        steps:
          - checkout
          - run:
              name: Install Docker Compose
              command: |
                curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
                chmod +x ~/docker-compose
                sudo mv ~/docker-compose /usr/local/bin/docker-compose

          - run:
              name: Install python
              command: |
                sudo apt update
                sudo apt-cache search python
                sudo apt install -y python3
   
          - run:
              name: check version
              command: |
                sudo python3 --version
   
          - run:
              name: check ip
              command: |
                ip a

          - run:
              name: build docker
              command: |
                 pwd
                 ls
                 docker build -t mockssh . 
