version: 2
jobs:
  build:
        machine: true
        steps:
            - checkout
            - run:
                name: Upgrade node.js
                command: |
                    curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
                    sudo apt-get install -y nodejs
                    node -v
            - run: npm run build:prod
            - run: docker-compose up -d
            - run: npm run test-e2e
