version: 2
jobs:
  build:
        machine: true
        steps:
            - checkout
            - run:
                name: Install python
                command: |
                  sudo apt install -y python3 python

            - run:
                name: check version
                command: |
                  python --version

            - run:
                name: check ip
                command: |
                  ip a
