version: 2
jobs:
  build:
        machine: true
        steps:
            - checkout
            - run:
                name: spin up docker
                command: |
                   docker run -d --name db circleci/node

            - run:
                name: verify docker
                command: |
                   docker ps -a
