version: 2
jobs:
  build:
        docker:
           - image: circleci/python:2.7

        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: build docker
                command: |
                   pwd
                   ls
                   docker build -t mockssh .

            - run:
                name: spin up docker
                command: |
                   docker run -d --name mockssh mockssh
                   pwd
                   ls

            - run:
                name: verify docker
                command: |
                   docker ps -a
                   docker inspect mockssh | grep -i ip
