version: 2
jobs:
  build:
        machine:
                image: ubuntu-1604:201903-01

        steps:
          - checkout
          - run:
              name: Install Docker Compose
              command: |
                curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
                chmod +x ~/docker-compose
                sudo mv ~/docker-compose /usr/local/bin/docker-compose

          - run:
              name: Install python
              command: |
                sudo apt update
                sudo apt-cache search python
                sudo apt install -y python3
   
          - run:
              name: check version
              command: |
                sudo python3 --version
   
          - run:
              name: check ip
              command: |
                ip a

          - run:
              name: build docker
              command: |
                 pwd
                 ls
                 docker build -t mockssh . 

          - run:
              name: spin up docker
              command: |
                 docker run -d --name mockssh mockssh

          - run:
              name: verify docker
              command: |
                 whoami
                 uname -a
                 docker ps -a
                 ip a
                 IP=$(docker inspect mockssh | grep -w IPAddress | awk '{print $2}' | tr -d '"' | tr -d ',' | tail -1)
                 echo $IP
                 sudo ping -c1 $IP

                 echo $DOCKER_HOST

                 IP2=$(echo $DOCKER_HOST | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")
                 echo ping ip2
                 ssh testadmin@$IP2
                 sudo ping c1 $IP2
                 sudo ip a
                 sudo ping -c1 $IP
                 sudo nc -z $IP 22
                 echo $?
                 ssh testadmin@$IP


