version: 2
jobs:
  build:
        machine: true
        steps:
            - checkout
            - run:
                name: spin up docker
                command: |
                   docker build -t mockssh .
                   docker run -d --name mockssh mockssh

            - run:
                name: verify docker
                command: |
                   docker ps -a
